name = "NAU"
version = 0
author = "Antonio Leitao"
url =  "https://github.com/antonio-leitao/nau"
email = "aleitao@novaims.unl.pt"
remote =  "https://github.com/antonio-leitao"
base_color = "#814584" #fandango (actually Plum)
projects_path = "/Users/antonio/Documents/Projects"
templates_path = "/Users/antonio/Documents/Templates"